import { createFileRoute, Link } from "@tanstack/react-router";
import { pageMeta } from "@/lib/seo";

export const Route = createFileRoute("/disclaimer")({
  head: () =>
    pageMeta({
      title: "Financial Disclaimer - MoneyCalc",
      description:
        "MoneyCalc provides estimates only. Read our financial disclaimer before using our calculators. Not financial advice.",
      path: "/disclaimer",
    }),
  component: DisclaimerPage,
});

function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6">
      <nav className="text-xs text-muted-foreground" aria-label="Breadcrumb">
        <Link to="/" className="hover:text-foreground">
          Home
        </Link>
        <span className="px-1.5">/</span>
        <span className="text-foreground">Disclaimer</span>
      </nav>

      <h1 className="mt-4 text-3xl font-extrabold sm:text-4xl">Financial Disclaimer</h1>

      <div className="mt-8 space-y-8">
        <section>
          <h2 className="text-2xl font-bold">Effective Date: July 31, 2026</h2>
          <p className="mt-3 text-muted-foreground">
            This Financial Disclaimer ("Disclaimer") explains the limitations and assumptions of the
            calculators and tools provided on MoneyCalc. By using our Service, you acknowledge and
            agree to these terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold">1. Not Financial Advice</h2>
          <div className="mt-4 space-y-4">
            <p className="text-muted-foreground">
              <strong>IMPORTANT:</strong> The information provided by MoneyCalc calculators is for
              educational and informational purposes only. It does not constitute financial,
              investment, tax, legal, or any other type of professional advice.
            </p>
            <p className="text-muted-foreground">
              You should not act or refrain from acting on the basis of any content provided on or
              through MoneyCalc without seeking appropriate professional advice. Nothing on this
              website should be relied upon as a substitute for professional financial advice.
            </p>
            <p className="text-muted-foreground">
              Your use of any information on MoneyCalc is solely at your risk. The Service is
              designed to help you estimate and understand financial scenarios, but it cannot
              replace the guidance of a qualified financial advisor, accountant, attorney, or other
              professional who can assess your specific situation.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold">2. Educational Purposes Only</h2>
          <div className="mt-4 space-y-4">
            <p className="text-muted-foreground">
              All calculators, tools, and content on MoneyCalc are provided for educational and
              illustrative purposes. They are intended to help you:
            </p>
            <ul className="list-disc space-y-2 pl-5 text-muted-foreground">
              <li>Understand financial concepts and formulas</li>
              <li>Estimate potential outcomes of financial decisions</li>
              <li>Compare different financial scenarios</li>
              <li>Plan and budget for future financial goals</li>
            </ul>
            <p className="text-muted-foreground">
              The results generated by our calculators are estimates based on the information you
              provide and the assumptions built into our formulas. They do not represent a guarantee
              of actual results.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold">3. Always Consult Professionals</h2>
          <div className="mt-4 space-y-4">
            <p className="text-muted-foreground">
              Before making any significant financial decision, you should consult with qualified
              professionals who can provide personalized advice based on your specific
              circumstances. These professionals can help you:
            </p>
            <ul className="list-disc space-y-2 pl-5 text-muted-foreground">
              <li>Assess your complete financial situation</li>
              <li>Understand tax implications of financial decisions</li>
              <li>Evaluate investment opportunities and risks</li>
              <li>Plan for retirement, education, and other long-term goals</li>
              <li>Navigate complex financial products and regulations</li>
            </ul>
            <p className="text-muted-foreground">
              Financial professionals can provide advice tailored to your unique needs, risk
              tolerance, and financial objectives in ways that generic calculators cannot.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold">4. Calculation Assumptions</h2>
          <div className="mt-4 space-y-4">
            <p className="text-muted-foreground">
              All our calculators use specific assumptions to produce results. These assumptions are
              clearly documented for each calculator, but you should understand that:
            </p>
            <ul className="list-disc space-y-2 pl-5 text-muted-foreground">
              <li>
                <strong>Fixed rates:</strong> Most calculators assume interest rates remain constant
                over the entire period, which may not reflect real-world scenarios with variable
                rates.
              </li>
              <li>
                <strong>Regular payments:</strong> Calculations assume consistent payment amounts
                throughout the term, without missed or late payments.
              </li>
              <li>
                <strong>No fees:</strong> Many calculators do not include fees such as loan
                origination fees, late fees, prepayment penalties, or account maintenance fees.
              </li>
              <li>
                <strong>Constant conditions:</strong> Some calculators assume property tax rates,
                insurance premiums, or other costs remain unchanged over time.
              </li>
              <li>
                <strong>Simpler scenarios:</strong> Real financial situations are often more
                complex, with additional variables not included in our simplified models.
              </li>
            </ul>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold">5. Possible Rounding Differences</h2>
          <div className="mt-4 space-y-4">
            <p className="text-muted-foreground">
              The results displayed by our calculators may differ slightly from manual calculations
              due to rounding. We round currency values to two decimal places for display purposes,
              but internal calculations may use more precision.
            </p>
            <p className="text-muted-foreground">
              Small differences may also occur between our calculators and other tools due to:
            </p>
            <ul className="list-disc space-y-2 pl-5 text-muted-foreground">
              <li>Different rounding methods (banker's rounding, standard rounding, etc.)</li>
              <li>Different compounding frequencies (monthly vs. daily vs. annual)</li>
              <li>Different handling of leap years and varying month lengths</li>
              <li>Different conventions for interest calculation</li>
            </ul>
            <p className="text-muted-foreground">
              These differences are normal and should not be considered errors. For precise
              calculations, always refer to your lender's or financial institution's official
              documentation.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold">6. Limitations of Calculator Models</h2>
          <div className="mt-4 space-y-4">
            <p className="text-muted-foreground">
              Our calculators are simplified models designed to illustrate financial concepts. They
              may not account for all factors that could affect your actual results:
            </p>
            <ul className="list-disc space-y-2 pl-5 text-muted-foreground">
              <li>
                <strong>Tax considerations:</strong> Most calculators do not account for tax
                implications, which can significantly affect after-tax returns and costs.
              </li>
              <li>
                <strong>Inflation:</strong> While some calculators include inflation adjustments,
                many do not, and inflation rates can vary significantly over time.
              </li>
              <li>
                <strong>Investment volatility:</strong> Investment calculators assume constant
                returns, while real markets are volatile and unpredictable.
              </li>
              <li>
                <strong>Credit risk:</strong> Loan calculators do not account for changes in credit
                score or eligibility requirements.
              </li>
              <li>
                <strong>Market conditions:</strong> Real estate, auto, and other loan values can
                fluctuate based on market conditions.
              </li>
            </ul>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold">7. No Guarantee of Accuracy</h2>
          <div className="mt-4 space-y-4">
            <p className="text-muted-foreground">
              While we use industry-standard formulas and strive for accuracy, we do not guarantee
              that all calculations will be error-free or suitable for your particular purpose.
            </p>
            <p className="text-muted-foreground">
              The Service and all its content are provided "as is" and "as available" without any
              warranties of any kind, either express or implied. We make no warranties,
              representations, or guarantees of any kind concerning the accuracy, reliability, or
              completeness of the information provided.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold">8. Third-Party Information</h2>
          <div className="mt-4 space-y-4">
            <p className="text-muted-foreground">
              Our calculators may reference or incorporate information from third-party sources. We
              do not endorse or guarantee the accuracy of information from these sources. The
              inclusion of third-party references does not imply any affiliation or endorsement by
              MoneyCalc.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold">9. Your Responsibility</h2>
          <div className="mt-4 space-y-4">
            <p className="text-muted-foreground">
              By using our calculators, you acknowledge that you are responsible for:
            </p>
            <ul className="list-disc space-y-2 pl-5 text-muted-foreground">
              <li>Verifying the accuracy of any data you input</li>
              <li>Understanding the assumptions underlying each calculation</li>
              <li>Consulting with appropriate professionals for personalized advice</li>
              <li>Considering all relevant factors in your financial decisions</li>
              <li>Reviewing and understanding the results before making decisions</li>
            </ul>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold">10. Changes to This Disclaimer</h2>
          <div className="mt-4 space-y-4">
            <p className="text-muted-foreground">
              We may update this Disclaimer from time to time. When we make changes, we will update
              the "Effective Date" at the top of this page. We encourage you to review this
              Disclaimer periodically for any changes.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold">11. Contact Us</h2>
          <div className="mt-4 space-y-4">
            <p className="text-muted-foreground">
              If you have any questions about this Disclaimer or our calculators, please contact us:
            </p>
            <div className="rounded-2xl border border-border bg-card p-4">
              <p className="font-medium">Email: support@moneycalc.com</p>
              <p className="text-muted-foreground mt-1">MoneyCalc, Attn: Support Team</p>
            </div>
          </div>
        </section>
      </div>

      <div className="mt-12 rounded-2xl border border-border bg-card p-6">
        <h3 className="text-lg font-semibold">Last Updated</h3>
        <p className="mt-2 text-muted-foreground">
          This Financial Disclaimer was last updated on July 31, 2026. Please review it periodically
          for any changes.
        </p>
      </div>
    </div>
  );
}
